"""empty message

Revision ID: 29b05e08a6bf
Revises: 583351a57f22
Create Date: 2021-02-16 11:29:05.932704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b05e08a6bf'
down_revision = '583351a57f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_program',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('program_code', sa.String(length=80), nullable=True),
    sa.Column('program_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('program_id'),
    sa.UniqueConstraint('program_code')
    )
    op.create_table('student_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_username', sa.String(length=80), nullable=True),
    sa.Column('program_code', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['program_code'], ['academic_program.program_code'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_names.student_id'], ),
    sa.ForeignKeyConstraint(['student_username'], ['student_names.student_username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_program')
    op.drop_table('academic_program')
    # ### end Alembic commands ###
