"""empty message

Revision ID: 7216d1e14681
Revises: 29b05e08a6bf
Create Date: 2021-03-15 15:10:22.185126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7216d1e14681'
down_revision = '29b05e08a6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_username', sa.String(length=80), nullable=True),
    sa.Column('course', sa.String(length=20), nullable=True),
    sa.Column('course_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_names.student_id'], ),
    sa.ForeignKeyConstraint(['student_username'], ['student_names.student_username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_course')
    # ### end Alembic commands ###
