"""empty message

Revision ID: ae6c0c723a02
Revises: cd8c199384da
Create Date: 2021-02-10 17:08:43.455796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6c0c723a02'
down_revision = 'cd8c199384da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_names',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_username', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('student_username')
    )
    op.drop_table('STUDENT_NAMES')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('STUDENT_NAMES',
    sa.Column('student_id', sa.INTEGER(), server_default=sa.text('nextval(\'"STUDENT_NAMES_student_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('student_username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('student_id', name='STUDENT_NAMES_pkey'),
    sa.UniqueConstraint('student_username', name='STUDENT_NAMES_student_username_key')
    )
    op.drop_table('student_names')
    # ### end Alembic commands ###
