"""empty message

Revision ID: cd8c199384da
Revises: b52c06328a8d
Create Date: 2021-02-10 17:06:48.546134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8c199384da'
down_revision = 'b52c06328a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('STUDENT_NAMES',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_username', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('student_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('STUDENT_NAMES')
    # ### end Alembic commands ###
